---
title: "TidyX"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# TidyX

This is notes and code from **Patrick Ward** and **Ellis Hughes's** TidyX tutorials.

## **TIDYX 1**

-   Use case\_when instead of nested ifelse, easier for people to understand your logic

-   Convert characters to Factors when you want to specify the order for plotting

-   Stringr::word() - extract words from a sentance

## **TIDYX 2**

-   Load "plyr" always before "dplyr" - due to namespace collision (dplyr has better functions with same names)

-   tidytext::stop\_words function removes words from sentiment analysis that done have any meaning (eg: an)

## **TIDYX 3**

-   use coord\_polar argument after a geom\_col, to spin the columns into a polar chart

-   Conflicted package can be used to specify which package you want to use like using double colon dplyr::

-   When converting chacter to numeric, make sure it is character and not factor. If you convert factor to numeric it will output the factors level**IDYX 4**

## **TIDYX 4**

-   geom\_density\_ridges to display density plots of all variables

-   patchwork - can be used to combine multiple plots with easy syntax

-   subplot() from plotly package to combine interactive plots

## **TIDYX 5**

-   use ungroup() after a group\_by() argument if you want to continue other processing steps but not on the grouped data

-   gganimate::transition\_reveal= plots then moves to the next frame and plots again, while retraining all previous frame plots

-   gganimate::animate(): use end\_pause = 12 to pause the end of the animation before it starts again
